# Generated by Django 5.2.3 on 2025-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('class_type', models.CharField(choices=[('web', 'Web Development'), ('app', 'App Development')], max_length=50)),
                ('class_option', models.CharField(choices=[('jhs_leavers', 'JHS Leavers (July 8th)'), ('jhs_weekend', 'JHS Weekend (Soon)'), ('shs_vacation', 'SHS Vacation (Soon)')], max_length=50)),
                ('payment_details', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
