# Generated by Django 5.2.3 on 2025-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reference',
            field=models.CharField(default='pending_ref', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
