# Generated by Django 5.2.3 on 2025-06-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registration_reference_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_details',
        ),
        migrations.AlterField(
            model_name='registration',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
